//! The app's own assets (den's preset logos and glyphs) in front of GPUI
//! Kit's icons. Generated by listing `assets/presets`; add a file there and a
//! line here.

use std::borrow::Cow;

use gpui_kit::{AssetSource, Result, SharedString};

static FILES: &[(&str, &[u8])] = &[
    ("presets/logos/claude.svg", include_bytes!("../assets/presets/logos/claude.svg")),
    ("presets/logos/claude-color.svg", include_bytes!("../assets/presets/logos/claude-color.svg")),
    ("presets/logos/openai.svg", include_bytes!("../assets/presets/logos/openai.svg")),
    ("presets/logos/antigravity.svg", include_bytes!("../assets/presets/logos/antigravity.svg")),
    ("presets/logos/antigravity-color.svg", include_bytes!("../assets/presets/logos/antigravity-color.svg")),
    ("presets/logos/codex.svg", include_bytes!("../assets/presets/logos/codex.svg")),
    ("presets/logos/codex-color.svg", include_bytes!("../assets/presets/logos/codex-color.svg")),
    ("presets/logos/githubcopilot.svg", include_bytes!("../assets/presets/logos/githubcopilot.svg")),
    ("presets/logos/cursor.svg", include_bytes!("../assets/presets/logos/cursor.svg")),
    ("presets/logos/amp.svg", include_bytes!("../assets/presets/logos/amp.svg")),
    ("presets/logos/amp-color.svg", include_bytes!("../assets/presets/logos/amp-color.svg")),
    ("presets/logos/opencode.svg", include_bytes!("../assets/presets/logos/opencode.svg")),
    ("presets/logos/goose.svg", include_bytes!("../assets/presets/logos/goose.svg")),
    ("presets/logos/kimi.svg", include_bytes!("../assets/presets/logos/kimi.svg")),
    ("presets/logos/kimi-color.svg", include_bytes!("../assets/presets/logos/kimi-color.svg")),
    ("presets/logos/qwen.svg", include_bytes!("../assets/presets/logos/qwen.svg")),
    ("presets/logos/qwen-color.svg", include_bytes!("../assets/presets/logos/qwen-color.svg")),
    ("presets/logos/mistral.svg", include_bytes!("../assets/presets/logos/mistral.svg")),
    ("presets/logos/mistral-color.svg", include_bytes!("../assets/presets/logos/mistral-color.svg")),
    ("presets/logos/cline.svg", include_bytes!("../assets/presets/logos/cline.svg")),
    ("presets/logos/kilocode.svg", include_bytes!("../assets/presets/logos/kilocode.svg")),
    ("presets/logos/kiro.svg", include_bytes!("../assets/presets/logos/kiro.svg")),
    ("presets/logos/kiro-color.svg", include_bytes!("../assets/presets/logos/kiro-color.svg")),
    ("presets/logos/junie.svg", include_bytes!("../assets/presets/logos/junie.svg")),
    ("presets/logos/junie-color.svg", include_bytes!("../assets/presets/logos/junie-color.svg")),
    ("presets/logos/openhands.svg", include_bytes!("../assets/presets/logos/openhands.svg")),
    ("presets/logos/openhands-color.svg", include_bytes!("../assets/presets/logos/openhands-color.svg")),
    ("presets/glyphs/number-one.svg", include_bytes!("../assets/presets/glyphs/number-one.svg")),
    ("presets/glyphs/number-two.svg", include_bytes!("../assets/presets/glyphs/number-two.svg")),
    ("presets/glyphs/number-three.svg", include_bytes!("../assets/presets/glyphs/number-three.svg")),
    ("presets/glyphs/number-four.svg", include_bytes!("../assets/presets/glyphs/number-four.svg")),
    ("presets/glyphs/terminal-window.svg", include_bytes!("../assets/presets/glyphs/terminal-window.svg")),
    ("presets/glyphs/code.svg", include_bytes!("../assets/presets/glyphs/code.svg")),
    ("presets/glyphs/bug.svg", include_bytes!("../assets/presets/glyphs/bug.svg")),
    ("presets/glyphs/flask.svg", include_bytes!("../assets/presets/glyphs/flask.svg")),
    ("presets/glyphs/rocket.svg", include_bytes!("../assets/presets/glyphs/rocket.svg")),
    ("presets/glyphs/lightning.svg", include_bytes!("../assets/presets/glyphs/lightning.svg")),
    ("presets/glyphs/sparkle.svg", include_bytes!("../assets/presets/glyphs/sparkle.svg")),
    ("presets/glyphs/robot.svg", include_bytes!("../assets/presets/glyphs/robot.svg")),
    ("presets/glyphs/brain.svg", include_bytes!("../assets/presets/glyphs/brain.svg")),
    ("presets/glyphs/magic-wand.svg", include_bytes!("../assets/presets/glyphs/magic-wand.svg")),
    ("presets/glyphs/lightbulb.svg", include_bytes!("../assets/presets/glyphs/lightbulb.svg")),
    ("presets/glyphs/fire.svg", include_bytes!("../assets/presets/glyphs/fire.svg")),
    ("presets/glyphs/star.svg", include_bytes!("../assets/presets/glyphs/star.svg")),
    ("presets/glyphs/heart.svg", include_bytes!("../assets/presets/glyphs/heart.svg")),
    ("presets/glyphs/crown.svg", include_bytes!("../assets/presets/glyphs/crown.svg")),
    ("presets/glyphs/ghost.svg", include_bytes!("../assets/presets/glyphs/ghost.svg")),
    ("presets/glyphs/cpu.svg", include_bytes!("../assets/presets/glyphs/cpu.svg")),
    ("presets/glyphs/database.svg", include_bytes!("../assets/presets/glyphs/database.svg")),
    ("presets/glyphs/cloud.svg", include_bytes!("../assets/presets/glyphs/cloud.svg")),
    ("presets/glyphs/globe.svg", include_bytes!("../assets/presets/glyphs/globe.svg")),
    ("presets/glyphs/package.svg", include_bytes!("../assets/presets/glyphs/package.svg")),
    ("presets/glyphs/wrench.svg", include_bytes!("../assets/presets/glyphs/wrench.svg")),
    ("presets/glyphs/gear-six.svg", include_bytes!("../assets/presets/glyphs/gear-six.svg")),
    ("presets/glyphs/git-branch.svg", include_bytes!("../assets/presets/glyphs/git-branch.svg")),
    ("presets/glyphs/bars-one.svg", include_bytes!("../assets/presets/glyphs/bars-one.svg")),
    ("presets/glyphs/bars-two.svg", include_bytes!("../assets/presets/glyphs/bars-two.svg")),
    ("presets/glyphs/bars-three.svg", include_bytes!("../assets/presets/glyphs/bars-three.svg")),
    ("presets/glyphs/bars-four.svg", include_bytes!("../assets/presets/glyphs/bars-four.svg")),
];

pub struct Assets;

impl AssetSource for Assets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        match FILES.iter().find(|(name, _)| *name == path) {
            Some((_, bytes)) => Ok(Some(Cow::Borrowed(bytes))),
            None => gpui_kit::assets::AllAssets.load(path),
        }
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        let mut list = gpui_kit::assets::AllAssets.list(path)?;
        list.extend(FILES.iter().filter(|(name, _)| name.starts_with(path)).map(|(name, _)| SharedString::from(*name)));
        Ok(list)
    }
}
